image: Ubuntu1804
stack: ruby 2.5
skip_commits:
  files:
    - index.xml
install:
  - gem install reapack-index --pre

  - sudo apt-get update -qq
  - sudo apt-get install pandoc -qq
build: off
test_script: reapack-index --check
deploy_script:
  if [[ "$APPVEYOR_REPO_BRANCH" == "master" ]]; then .ci/deploy.sh; fi
